image: nexendrie/php:8.1

stages:
  - test
  - deploy

cache:
  paths:
  - vendor/

before_script:
  - composer update --prefer-dist --no-progress --no-suggest --no-interaction

.job_template: &test_job
  stage: test
  script:
  - phing test

test:php8.1:
  <<: *test_job
  image: nexendrie/php:8.1

test:php8.1:lowest-deps:
  <<: *test_job
  image: nexendrie/php:8.1
  before_script:
    - composer update --prefer-lowest --prefer-dist --no-progress --no-suggest --no-interaction

test:php8.2:
  <<: *test_job
  image: nexendrie/php:8.2

test:php8.2:lowest-deps:
  <<: *test_job
  image: nexendrie/php:8.2
  before_script:
    - composer update --prefer-lowest --prefer-dist --no-progress --no-suggest --no-interaction

test:cc:
  <<: *test_job
  script:
  - phing test-coverage
  coverage: '/(\d+\%) covered/'

pages:
  stage: deploy
  environment:
    name: documentation
    url: https://nexendrie.gitlab.io/utils
  script:
  - phing documentation
  artifacts:
      paths:
      - public
  only:
  - tags@nexendrie/utils
